services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blackjack
      MYSQL_USER: blackjackuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blackjack_network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blackjack_network

  app:
    build: .
    container_name: blackjack_app
    restart: always
    depends_on:
      - mysql
      - mongo
    env_file:
      - .env
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/blackjack
      SPRING_R2DBC_USERNAME: blackjackuser
      SPRING_R2DBC_PASSWORD: 1234
      SPRING_DATA_MONGODB_URI: mongodb://admin:1234@mongo_db:27017/blackjack?authSource=admin
    ports:
      - "8080:8080"
    networks:
      - blackjack_network

networks:
  blackjack_network:

volumes:
  mysql_data:
  mongo_data: